version: "3.8"

services:
  influxdb:
    container_name: "influx_db_dev"
    image: influxdb:latest
    restart: always
    ports:
      - 8086:8086 # Publicly expose InfluxDB
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=***USERNAME***
      - DOCKER_INFLUXDB_INIT_PASSWORD=***PASSWORD***
      - DOCKER_INFLUXDB_INIT_ORG=***ORG***
      - DOCKER_INFLUXDB_INIT_BUCKET=***BUCKET***
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=***TOKEN***
    volumes:
      - ./database/data:/var/lib/influxdb2
      - ./database/config:/etc/influxdb2