version: "3.8"

services:
  influxdb:
    container_name: "influx_db_dev"
    image: influxdb:latest
    restart: always
    ports:
      - 8086:8086 # Publicly expose InfluxDB
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_DB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_DB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_DB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_DB_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_DB_ADMIN_TOKEN}
    volumes:
      - ./database/data:/var/lib/influxdb2
      - ./database/config:/etc/influxdb2